from typing import List

from sc2.ids.unit_typeid import UnitTypeId
from sc2.ids.upgrade_id import UpgradeId


class BuildStarts():
    def get_build_start(build_name: str) -> List[UnitTypeId]:
        if build_name == "empty":
            return []
        elif build_name == "test":
            return [
                # UnitTypeId.THOR,
                # UnitTypeId.BARRACKS,
                # UnitTypeId.REFINERY,
                # UnitTypeId.BARRACKSTECHLAB,
                # UpgradeId.SHIELDWALL
            ]
        elif build_name == "pig_b2gm":
            # this needs actual units
            return [
                UnitTypeId.SUPPLYDEPOT,                 # wall at ramp or main edge,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.REAPER,
                UnitTypeId.MARINE,
                UnitTypeId.ORBITALCOMMAND,              # MAIN,
                UnitTypeId.COMMANDCENTER,               # NATURAL, on location if safe,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORY,
                UnitTypeId.FACTORYTECHLAB,              # fast SIEGETANK access,
                UnitTypeId.SIEGETANK,                   # start as soon as TECHLAB is ready,
                UnitTypeId.REFINERY,                    # 2ND GAS,
                UnitTypeId.SIEGETANK,                   # start as soon as TECHLAB is ready,
                # UnitTypeId.BUNKER,                      # NATURAL choke,
                UnitTypeId.MARINE,               # begin reactor cycles,
                UnitTypeId.MARINE,               # begin reactor cycles,
# from here, keep SCV and MULE production constant until ~45 workers (author logic)
                UnitTypeId.STARPORT,
                UnitTypeId.VIKINGFIGHTER,               # safer baseline scout vs all races (LIBERATOR optional),
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.ORBITALCOMMAND,              # NATURAL,
                UnitTypeId.MARINE,                   # begin reactor cycles,
                UnitTypeId.MARINE,                   # begin reactor cycles,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORYREACTOR,              # build REACTOR, then SWAP: lift FACTORY, land STARPORT on this REACTOR for MEDIVAC,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.FACTORYTECHLAB,              # rebuild TECHLAB on FACTORY, resume SIEGETANK,

# you may PAUSE STARPORT and extra FACTORY units until 4x BARRACKS start and upgrades begin, then resume MEDIVAC and SIEGETANK

# POWER SPIKE SETUP
                UnitTypeId.ENGINEERINGBAY,              # start TERRANINFANTRYWEAPONSLEVEL1 when ready,
                UnitTypeId.BARRACKS,
                UnitTypeId.BARRACKS,
                UnitTypeId.BARRACKS,
                UnitTypeId.BARRACKS,
                UnitTypeId.BARRACKSTECHLAB,
                UnitTypeId.BARRACKSTECHLAB,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.BARRACKSREACTOR,
                UpgradeId.TERRANINFANTRYWEAPONSLEVEL1,
                UnitTypeId.MEDIVAC,                  # double MEDIVAC off the swapped STARPORT; if using SILVER pause, slide later,
                UnitTypeId.MEDIVAC,                  # double MEDIVAC off the swapped STARPORT; if using SILVER pause, slide later,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.MARAUDER,
                UnitTypeId.MARAUDER,

# GAS ROUND-OUT AND UPGRADES
                UnitTypeId.REFINERY,                    # 3RD GAS (NATURAL),
                UnitTypeId.REFINERY,                    # 4TH GAS (NATURAL),
                UpgradeId.STIMPACK,
                UpgradeId.SHIELDWALL,                  # Combat Shields,
                UpgradeId.PUNISHERGRENADES,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MEDIVAC,                  # continuous pairs as gas allows,
                UnitTypeId.MEDIVAC,                  # continuous pairs as gas allows,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,

# RHYTHM TO FIRST TIMING
                UnitTypeId.MARAUDER,                 # from TECHLAB RAX,
                UnitTypeId.MARAUDER,                 # from TECHLAB RAX,
                UnitTypeId.MARINE,                   # keep Reactor cycles going,
                UnitTypeId.MARINE,                   # keep Reactor cycles going,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SUPPLYDEPOT,

                # UnitTypeId.SUPPLYDEPOT,
                # UnitTypeId.BARRACKS,
                # UnitTypeId.REFINERY,
                # UnitTypeId.ORBITALCOMMAND,
                # UnitTypeId.BARRACKSREACTOR,
                # UnitTypeId.MARINE,
                # UnitTypeId.MARINE,
                # UnitTypeId.COMMANDCENTER,
                # UnitTypeId.SUPPLYDEPOT,
                # UnitTypeId.FACTORY,
                # UnitTypeId.FACTORYTECHLAB,
                # UnitTypeId.REFINERY,
                # UnitTypeId.MARINE,
                # UnitTypeId.BUNKER,
                # UnitTypeId.MARINE,
                # UnitTypeId.SIEGETANK,
                # UnitTypeId.STARPORT,
                # UnitTypeId.MARINE,
                # UnitTypeId.STARPORTREACTOR,
                # UnitTypeId.MEDIVAC,
                # UnitTypeId.MARINE,
                # UnitTypeId.BARRACKS,
                # UnitTypeId.MARINE,
                # UnitTypeId.MARINE,
                # UnitTypeId.MARINE,
                # UnitTypeId.BARRACKS,
                # UnitTypeId.MARINE,
                # UnitTypeId.BARRACKS,
                # UnitTypeId.BARRACKS,
                # UnitTypeId.BARRACKSTECHLAB,
                # UnitTypeId.MARINE,
                # UnitTypeId.BARRACKSREACTOR,
                # UnitTypeId.BARRACKSREACTOR,
                # UnitTypeId.ENGINEERINGBAY,
                # UnitTypeId.MARINE,
                # UnitTypeId.REFINERY,
                # UnitTypeId.REFINERY,
                # UpgradeId.STIMPACK,
                # UpgradeId.SHIELDWALL,
                # UpgradeId.PUNISHERGRENADES,
                # UpgradeId.TERRANINFANTRYWEAPONSLEVEL1,
                # UnitTypeId.SUPPLYDEPOT,
                # UnitTypeId.ARMORY,
            ]
        elif build_name == "tvt1":
            # https://lotv.spawningtool.com/build/171779/
            # Standard Terran vs Terran (3 Reaper 2 Hellion) (TvT Economic)
            # Very Standard Reaper Hellion Opening that transitions into Marine-Tank-Raven. As solid it as it gets
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.REFINERY,
                UnitTypeId.REAPER,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORY,
                UnitTypeId.REAPER,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.HELLION,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.REAPER,
                UnitTypeId.STARPORT,
                UnitTypeId.HELLION,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.REFINERY,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.CYCLONE,
                UnitTypeId.MARINE,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.STARPORTTECHLAB,
                UnitTypeId.SIEGETANK,
                UnitTypeId.RAVEN,
            ]
        elif build_name == "tvt2":
            # tweaked tvt1
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.REAPER,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORY,
                UnitTypeId.REAPER,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SIEGETANK,
                UnitTypeId.REFINERY,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.STARPORT,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.STARPORTTECHLAB,
                UnitTypeId.SIEGETANK,
                UnitTypeId.RAVEN,
            ]
        elif build_name == 'bottato1':
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.MARINE,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.REAPER,
                UnitTypeId.REFINERY,
                UnitTypeId.FACTORY,
                UnitTypeId.REAPER,
                UnitTypeId.CYCLONE,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.REFINERY,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SIEGETANK,
                UnitTypeId.STARPORT,
                UnitTypeId.STARPORTTECHLAB,
                UnitTypeId.RAVEN,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.REFINERY,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.RAVEN,
                UnitTypeId.SIEGETANK,
                UnitTypeId.ENGINEERINGBAY,
                UnitTypeId.RAVEN,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SIEGETANK,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.ARMORY,
                UnitTypeId.SIEGETANK,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.REFINERY,
                UnitTypeId.REFINERY,
                UnitTypeId.BARRACKSTECHLAB,
                UnitTypeId.FACTORY,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.FACTORY,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SIEGETANK,
                UnitTypeId.HELLION,
                UnitTypeId.HELLION,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.HELLION,
                UnitTypeId.HELLION,
                UnitTypeId.FACTORY,
                UnitTypeId.FACTORY,
                UnitTypeId.COMMANDCENTER,
            ]
