from typing import List

from sc2.ids.unit_typeid import UnitTypeId
from sc2.ids.upgrade_id import UpgradeId


class BuildStarts():
    def get_build_start(build_name: str) -> List[UnitTypeId]:
        if build_name == "empty":
            return []
        elif build_name == "test":
            return [
                # UnitTypeId.THOR,
                # UnitTypeId.BARRACKS,
                # UnitTypeId.REFINERY,
                # UnitTypeId.BARRACKSTECHLAB,
                # UpgradeId.SHIELDWALL
            ]
        elif build_name == "pig_b2gm":
            return [
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.SUPPLYDEPOT,                 # wall at ramp or main edge,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.REFINERY,                    # 2ND GAS,
                UnitTypeId.REAPER, # XXX harass
                UnitTypeId.ORBITALCOMMAND,              # MAIN,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORY, # XXX after reactor if getting cheesed
                UnitTypeId.COMMANDCENTER,               # NATURAL, on location if safe, pause SCVs to pay for this
                UnitTypeId.BARRACKSREACTOR, # XXX before factory if getting cheesed
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.BUNKER,                      # NATURAL choke, XXX on high ground if getting cheesed
                UnitTypeId.SCV,
                UnitTypeId.FACTORYTECHLAB,              # fast SIEGETANK access,
                UnitTypeId.SCV,
                UnitTypeId.SIEGETANK,                   # start as soon as TECHLAB is ready,
                UnitTypeId.SCV,
                UnitTypeId.MARINE,               # begin reactor cycles,
                UnitTypeId.MARINE,
# from here, keep SCV and MULE production constant until ~45 workers (author logic)
                UnitTypeId.SCV,   # supply blocked until comand center finishes
                UnitTypeId.SCV,
                UnitTypeId.STARPORT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.MEDIVAC, # early medivac good?
                UnitTypeId.SIEGETANK,
                UnitTypeId.BARRACKS,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.MARINE, # supply blocked until depot finishes
                UnitTypeId.MARINE,
                UnitTypeId.REFINERY,
                # UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SCV,
                UnitTypeId.VIKINGFIGHTER,               # safer baseline scout vs all races (LIBERATOR optional),
                UnitTypeId.ORBITALCOMMAND,              # NATURAL,
                UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.SCV,
                # UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SCV,  # pause SCVs again for next command center
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.STARPORTREACTOR,              # build REACTOR, then SWAP: lift FACTORY, land STARPORT on this REACTOR for MEDIVAC,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.STARPORT,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                # UnitTypeId.FACTORYTECHLAB,              # rebuild TECHLAB on FACTORY, resume SIEGETANK,

# you may PAUSE STARPORT and extra FACTORY units until 4x BARRACKS start and upgrades begin, then resume MEDIVAC and SIEGETANK

# POWER SPIKE SETUP
                # UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.ENGINEERINGBAY,              # start TERRANINFANTRYWEAPONSLEVEL1 when ready,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.REFINERY,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                # UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SCV,
                UnitTypeId.STARPORTTECHLAB,
                UpgradeId.TERRANINFANTRYWEAPONSLEVEL1,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.BARRACKS,
                UnitTypeId.BARRACKS,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                # UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MEDIVAC, # supply blocked until depot finishes
                UnitTypeId.RAVEN,
                UnitTypeId.BARRACKS,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE, # supply blocked until cc finishes
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SCV,
                UnitTypeId.MEDIVAC,
                # UnitTypeId.SCV,
                # UnitTypeId.SUPPLYDEPOT,
                # good until here
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                UnitTypeId.SCV,
                # UnitTypeId.SUPPLYDEPOT,
                # UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.REFINERY,
                UnitTypeId.BARRACKSTECHLAB,
                UnitTypeId.MARINE,
                UnitTypeId.BARRACKSTECHLAB,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                #
                UnitTypeId.SIEGETANK,
                # UnitTypeId.MEDIVAC,                  # double MEDIVAC off the swapped STARPORT; if using SILVER pause, slide later,
                # UnitTypeId.SCV,
                # UnitTypeId.SCV,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                # UnitTypeId.SCV,
                # UnitTypeId.SUPPLYDEPOT,
                # UnitTypeId.SCV,
                UpgradeId.STIMPACK,
                UpgradeId.SHIELDWALL,                  # Combat Shields, start as soon as techlab finishes
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.MARAUDER,
                # UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARAUDER,
# GAS ROUND-OUT AND UPGRADES
                UnitTypeId.REFINERY,
                UnitTypeId.REFINERY,
                UpgradeId.PUNISHERGRENADES,
                # UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MEDIVAC,                  # continuous pairs as gas allows,
                UnitTypeId.MEDIVAC,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,

# RHYTHM TO FIRST TIMING
                UnitTypeId.MARAUDER,                 # from TECHLAB RAX,
                UnitTypeId.MARAUDER,
                UnitTypeId.MARINE,                   # keep Reactor cycles going,
                UnitTypeId.MARINE,
                # UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SIEGETANK,
                # UnitTypeId.SUPPLYDEPOT,
            ]
        elif build_name == "tvt1":
            # https://lotv.spawningtool.com/build/171779/
            # Standard Terran vs Terran (3 Reaper 2 Hellion) (TvT Economic)
            # Very Standard Reaper Hellion Opening that transitions into Marine-Tank-Raven. As solid it as it gets
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.REFINERY,
                UnitTypeId.REAPER,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORY,
                UnitTypeId.REAPER,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.HELLION,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.REAPER,
                UnitTypeId.STARPORT,
                UnitTypeId.HELLION,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.REFINERY,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.CYCLONE,
                UnitTypeId.MARINE,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.STARPORTTECHLAB,
                UnitTypeId.SIEGETANK,
                UnitTypeId.RAVEN,
            ]
        elif build_name == "tvt2":
            # tweaked tvt1
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.REAPER,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORY,
                UnitTypeId.REAPER,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SIEGETANK,
                UnitTypeId.REFINERY,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.STARPORT,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.STARPORTTECHLAB,
                UnitTypeId.SIEGETANK,
                UnitTypeId.RAVEN,
            ]
        elif build_name == 'bottato1':
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.MARINE,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.REAPER,
                UnitTypeId.REFINERY,
                UnitTypeId.FACTORY,
                UnitTypeId.REAPER,
                UnitTypeId.CYCLONE,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.REFINERY,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SIEGETANK,
                UnitTypeId.STARPORT,
                UnitTypeId.STARPORTTECHLAB,
                UnitTypeId.RAVEN,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.REFINERY,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.RAVEN,
                UnitTypeId.SIEGETANK,
                UnitTypeId.ENGINEERINGBAY,
                UnitTypeId.RAVEN,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SIEGETANK,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.ARMORY,
                UnitTypeId.SIEGETANK,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.REFINERY,
                UnitTypeId.REFINERY,
                UnitTypeId.BARRACKSTECHLAB,
                UnitTypeId.FACTORY,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.FACTORY,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SIEGETANK,
                UnitTypeId.HELLION,
                UnitTypeId.HELLION,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.HELLION,
                UnitTypeId.HELLION,
                UnitTypeId.FACTORY,
                UnitTypeId.FACTORY,
                UnitTypeId.COMMANDCENTER,
            ]
