from typing import List

from sc2.ids.unit_typeid import UnitTypeId


class BuildStarts():
    def get_build_start(build_name: str) -> List[UnitTypeId]:
        if build_name == "empty":
            return []
        elif build_name == "test":
            return [
                # UnitTypeId.THOR,
                # UnitTypeId.BARRACKS,
                # UnitTypeId.REFINERY,
                # UnitTypeId.BARRACKSTECHLAB,
                # UpgradeId.SHIELDWALL
            ]
        elif build_name == "pig_b2gm":
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.REAPER,
                UnitTypeId.MARINE,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.MARINE,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORY,
                UnitTypeId.REFINERY,
                UnitTypeId.BUNKER,
                UnitTypeId.STARPORT
            ]
        elif build_name == "tvt1":
            # https://lotv.spawningtool.com/build/171779/
            # Standard Terran vs Terran (3 Reaper 2 Hellion) (TvT Economic)
            # Very Standard Reaper Hellion Opening that transitions into Marine-Tank-Raven. As solid it as it gets
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.REFINERY,
                UnitTypeId.REAPER,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORY,
                UnitTypeId.REAPER,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.HELLION,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.REAPER,
                UnitTypeId.STARPORT,
                UnitTypeId.HELLION,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.REFINERY,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.CYCLONE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.STARPORTTECHLAB,
                UnitTypeId.SIEGETANK,
                UnitTypeId.RAVEN,
            ]
        elif build_name == "tvt2":
            # tweaked tvt1
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.REAPER,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.FACTORY,
                UnitTypeId.REAPER,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.SIEGETANK,
                UnitTypeId.REFINERY,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.STARPORT,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.SIEGETANK,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.MEDIVAC,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.STARPORTTECHLAB,
                UnitTypeId.SIEGETANK,
                UnitTypeId.RAVEN,
            ]
        elif build_name == 'bottato1':
            return [
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.BARRACKS,
                UnitTypeId.REFINERY,
                UnitTypeId.BARRACKSREACTOR,
                UnitTypeId.MARINE,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.MARINE,
                UnitTypeId.MARINE,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.REAPER,
                UnitTypeId.REFINERY,
                UnitTypeId.FACTORY,
                UnitTypeId.REAPER,
                UnitTypeId.CYCLONE,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.REFINERY,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SIEGETANK,
                UnitTypeId.STARPORT,
                UnitTypeId.STARPORTTECHLAB,
                UnitTypeId.RAVEN,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.COMMANDCENTER,
                UnitTypeId.REFINERY,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.RAVEN,
                UnitTypeId.SIEGETANK,
                UnitTypeId.ENGINEERINGBAY,
                UnitTypeId.RAVEN,
                UnitTypeId.SUPPLYDEPOT,
                UnitTypeId.SIEGETANK,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.ORBITALCOMMAND,
                UnitTypeId.ARMORY,
                UnitTypeId.SIEGETANK,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.REFINERY,
                UnitTypeId.REFINERY,
                UnitTypeId.BARRACKSTECHLAB,
                UnitTypeId.FACTORY,
                UnitTypeId.FACTORYTECHLAB,
                UnitTypeId.FACTORY,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.SIEGETANK,
                UnitTypeId.SIEGETANK,
                UnitTypeId.HELLION,
                UnitTypeId.HELLION,
                UnitTypeId.VIKINGFIGHTER,
                UnitTypeId.HELLION,
                UnitTypeId.HELLION,
                UnitTypeId.FACTORY,
                UnitTypeId.FACTORY,
                UnitTypeId.COMMANDCENTER,
            ]
