class MagicNumbers:
    ## facts
    MULE_ENERGY_COST = 50

    ## opinions
    # workers
    MULE_AGE_LIMIT = 58
    SCAN_RESERVE_ENERGY = 60
    MAX_WORKERS_GLOBAL = 75
    MAX_WORKERS_PER_BASE = 25
    HEALTH_PER_REPAIRER = 50
    MAX_REPAIRERS = 10
    MULE_MIN_ENEMY_DISTANCE_SQ = 225
    WORKER_SPEED_MINE_RETREAT_HEALTH_PERCENT_THRESHOLD = 0.7
    WORKER_ATTACK_NEARBY_RETREAT_HEALTH_PERCENT_THRESHOLD = 0.6
    WORKER_ATTACK_NEARBY_ENEMY_RANGE = 3
    WORKER_ATTACK_NEARBY_ENEMY_RANGE_WORKER_RUSH = 8
    WORKER_ATTACK_RETREAT_HEALTH_THRESHOLD = 15
    WORKER_ATTACK_MINERAL_WALK_OBSTRUCTION_DISTANCE = 0.375
    WORKER_ATTACK_PULL_CUTOFF_TIME = 200
    WORKER_ATTACK_PULL_ENEMY_RANGE = 23
    WORKER_ATTACK_PULL_RANGE_SQ = 625
    WORKER_ATTACK_PULL_HEIGHT_RANGE = 5
    WORKER_ATTACK_PULL_RESERVE_MINERS = 2
    WORKER_ATTACK_PULL_EXTRA_DEFENDERS = 2
    WORKER_ATTACK_ENEMY_PREDICTION_SECONDS = 2.0
    WORKER_ATTACK_PER_ENEMY = 2
    WORKER_ATTACK_PER_PROBE_NO_STRUCTURES = 3
    WORKER_ATTACK_MINERAL_WALK_RETREAT_DISTANCE = 1.6
    WORKER_ATTACK_PRIORITIZE_REPAIR_HEALTH_PERCENT_THRESHOLD = 0.85
    WORKER_ATTACK_INJURED_REPAIR_NEARBY_RANGE = 4
    WORKER_ATTACK_HEALTHY_REPAIR_NEARBY_RANGE = 0.8
    IS_FACING_ANGLE_ERROR = 0.3
    MINERAL_MAX_DISTANCE_FROM_BASE = 15
    BUILDER_ALLOWED_IDLE_TIME = 5
    WORKER_REDISTRIBUTE_COOLDOWN = 3
    WORKER_REDISTRIBUTE_MAX_COUNT = 10
    WORKER_REDISTRIBUTE_VESPENE_BANK_TARGET = 90
    WORKER_REDISTRIBUTE_MINERAL_BANK_TARGET = 0
    WORKER_REPAIR_MIN_MINERALS = 20
    WORKER_REPAIR_PERCENT_ASSIGNED = 0.2
    WORKER_REPAIR_RAMP_WALL_TIME = 300
    WORKER_REPAIR_EARLY_RESPONSE_TIME = 180
    WORKER_REPAIR_EARLY_RESPONSE_COUNT = 5
    WORKER_REPAIR_EARLY_MAX_TARGETS = 5
    WORKER_REPAIR_PER_INJURED_MAX = 3
    WORKER_REPAIRER_HEALTH_PERCENT_THRESHOLD = 0.5
    WORKER_REPAIR_WORKER_MAX_DISTANCE = 10
    WORKER_REPAIR_MAX_DISTANCE = 60
    WORKER_REPAIR_LIMIT_DISTANCE_UNTIL_TIME = 540
    WORKER_REPAIR_DEFENSIVE_TANK_DISTANCE = 20
    AVOID_EFFECT_BUFFER = 1.2